name: Gradle Build

on:
  [push, fork]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Grant execute permission
      run: chmod +x gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
      with:
        arguments: build --scan
